name: Save data

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements.
      run: |-
        python -m pip install -U pip
    - name: Save data.
      run: python main.py
    - name: Push updated data.
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated cache @ ${timestamp}" || exit 0
        git push
